FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY . .


RUN ["dotnet", "tool", "install", "--global" ,"dotnet-ef"]
ENV DOTNET_TOOLS="/root/.dotnet/tools" \
    PATH="$PATH:/root/.dotnet/tools" \
    ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS=http://+:80 \
    ConnectionStrings__DefaultConnection="Server=sqlserver;Database=DevMatchDb;User Id=sa;Password=sqldb123#_@devmatch;TrustServerCertificate=True;"
ENTRYPOINT [ "dotnet", "watch"]
CMD [ "run", "--project", "DevMatch/DevMatch.csproj", "--no-launch-profile", "--urls", "http://+:80" ]